-- local M = {}
-- local api = vim.api
--
-- ---@param ns_id integer
-- function M.define_highlights(ns_id)
--     api.nvim_set_hl(ns_id, "SpeedtyperTypo", {
--
--     })
--     api.nvim_set_hl(ns_id, "SpeedtyperWpm", {
--
--     })
--     api.nvim_set_hl(ns_id, "SpeedtyperAccuracy", {
--
--     })
-- end
--
-- return M
