-- sentences from the phonetically rich CMU ARCTIC TTS prompts
-- http://festvox.org/cmu_arctic/
return {
    "Author of the danger trail, Philip Steels, etc.",
    "Not at this particular case, Tom, apologized Whittemore.",
    "For the twentieth time that evening the two men shook hands.",
    "Lord, but I'm glad to see you again, Phil.",
    "Will we ever forget it.",
    "God bless 'em, I hope I'll go on seeing them forever.",
    "And you always want to see it in the superlative degree.",
    "Gad, your letter came just in time.",
    "He turned sharply, and faced Gregson across the table.",
    "I'm playing a single hand in what looks like a losing game.",
    "If I ever needed a fighter in my life I need one now.",
    "Gregson shoved back his chair and rose to his feet.",
    "He was a head shorter than his companion, of almost delicate physique.",
    "Now you're coming down to business, Phil, he exclaimed.",
    "It's the aurora borealis.",
    "There's Fort Churchill, a rifle-shot beyond the ridge, asleep.",
    "From that moment his friendship for Belize turns to hatred and jealousy.",
    "There was a change now.",
    "I followed the line of the proposed railroad, looking for chances.",
    "Clubs and balls and cities grew to be only memories.",
    "It fairly clubbed me into recognizing it.",
    "Hardly were our plans made public before we were met by powerful opposition.",
    "A combination of Canadian capital quickly organized and petitioned for the same privileges.",
    "It was my reports from the north which chiefly induced people to buy.",
    "I was about to do this when cooler judgment prevailed.",
    "It occurred to me that there would have to be an accounting.",
    "To my surprise he began to show actual enthusiasm in my favor.",
    "Robbery, bribery, fraud, ",
    "Their forces were already moving into the north country.",
    "I had faith in them.",
    "They were three hundred yards apart.",
    "Since then some mysterious force has been fighting us at every step.",
    "He unfolded a long typewritten letter, and handed it to Gregson.",
    "Men of Selden's stamp don't stop at women and children.",
    "He stopped, and Philip nodded at the horrified question in his eyes.",
    "She turned in at the hotel.",
    "I was the only one who remained sitting.",
    "We'll have to watch our chances.",
    "The ship should be in within a week or ten days.",
    "I suppose you wonder why she is coming up here.",
    "Meanwhile I'll go out to breathe a spell.",
    "How could he explain his possession of the sketch.",
    "It seemed nearer to him since he had seen and talked with Gregson.",
    "Her own betrayal of herself was like tonic to Philip.",
    "He moved away as quietly as he had come.",
    "The girl faced him, her eyes shining with sudden fear.",
    "Close beside him gleamed the white fangs of the wolf-dog.",
    "He looked at the handkerchief more, closely.",
    "Gregson was asleep when he re-entered the cabin.",
    "In spite of their absurdity the words affected Philip curiously.",
    "The lace was of a delicate ivory color, faintly tinted with yellow.",
    "It was a curious coincidence.",
    "Suddenly his fingers closed tightly over the handkerchief.",
    "There was nothing on the rock.",
    "Philip stood undecided, his ears strained to catch the slightest sound.",
    "Pearce's little eyes were fixed on him shrewdly.",
    "I have no idea, replied Philip.",
    "I came for information more out of curiosity than anything else.",
    "His immaculate appearance was gone.",
    "Anyway, no one saw her like that.",
    "Philip snatched at the letter which Gregson held out to him.",
    "The men stared into each other's face.",
    "Yes, it was a man who asked, a stranger.",
    "The fourth and fifth days passed without any developments.",
    "They closed now until his fingers were like cords of steel.",
    "He saw Jeanne falter for a moment.",
    "Surely I will excuse you, she cried.",
    "In a flash Philip followed its direction.",
    "It was his intention to return to Eileen and her father.",
    "He would first hunt up Gregson and begin his work there.",
    "What was the object of your little sensation.",
    "But who was Eileen's double.",
    "The promoter's eyes were heavy, with little puffy bags under them.",
    "And now, down there, Eileen was waiting for him.",
    "There has been a change, she interrupted him.",
    "The gray eyes faltered; the flush deepened.",
    "It is the fire, partly, she said.",
    "Then, and at supper, he tried to fathom her.",
    "It was a large canoe.",
    "What if Jeanne failed him.",
    "What if she did not come to the rock.",
    "His face was streaming with blood.",
    "A shadow was creeping over Pierre's eyes.",
    "Scarcely had he uttered the name when Pierre's closing eyes shot open.",
    "A trickle of fresh blood ran over his face.",
    "Death had come with terrible suddenness.",
    "Philip bent lower, and stared into the face of the dead man.",
    "He made sure that the magazine was loaded, and resumed his paddling.",
    "The nightglow was treacherous to shoot by.",
    "The singing voice approached rapidly.",
    "His blood grew hot with rage at the thought.",
    "He went down in midstream, searching the shadows of both shores.",
    "For a full minute he crouched and listened.",
    "He had barely entered this when he saw the glow of a fire.",
    "A big canvas tent was the first thing to come within his vision.",
    "Perhaps she had already met her fate a little deeper in the forest.",
    "Then you can arrange yourself comfortably among these robes in the bow.",
    "Shall I carry you.",
    "A maddening joy pounded in his brain.",
    "You must sleep, he urged.",
    "You, you would not keep the truth from me.",
    "He will follow us soon.",
    "But there came no promise from the bow of the canoe.",
    "She was sleeping under his protection as sweetly as a child.",
    "Only, it is so wonderful, so almost impossible to believe.",
    "The emotion which she had suppressed burst forth now in a choking sob.",
    "If you only could know how I thank you.",
    "He waded into the edge of the water and began scrubbing himself.",
    "Do you know that you are shaking my confidence in you.",
    "Much, replied Jeanne, as tersely.",
    "Instead, he joined her; and they ate like two hungry children.",
    "He was wounded in the arm.",
    "I suppose you picked that lingo up among the Indians.",
    "Her words sent a strange chill through Philip.",
    "He had no excuse for the feelings which were aroused in him.",
    "Was it the rendezvous of those who were striving to work his ruin.",
    "She added, with genuine sympathy in her face and voice.",
    "Pierre obeys me when we are together.",
    "Jeanne was turning the bow shoreward.",
    "My right foot feels like that of a Chinese debutante.",
    "They ate dinner at the fifth, and rested for two hours.",
    "Two years ago I gave up civilization for this.",
    "She had died from cold and starvation.",
    "It was Jeanne singing softly over beyond the rocks.",
    "He was determined now to maintain a more certain hold upon himself.",
    "Each day she became a more vital part of him.",
    "It was a temptation, but he resisted it.",
    "This one hope was destroyed as quickly as it was born.",
    "Her face was against his breast.",
    "She was his now, forever.",
    "Providence had delivered him through the maelstrom.",
    "A cry of joy burst from Philip's lips.",
    "Philip began to feel that he had foolishly overestimated his strength.",
    "He obeyed the pressure of her hand.",
    "I am going to surprise father, and you will go with Pierre.",
    "About him, everywhere, were the evidences of luxury and of age.",
    "Then he stepped back with a low cry of pleasure.",
    "In the picture he saw each moment a greater resemblance to Jeanne.",
    "He told himself that as he washed himself and groomed his disheveled clothes.",
    "Accept a father's blessing, and with it, this.",
    "It seems like a strange pointing of the hand of God.",
    "Such things had occurred before, he told Philip.",
    "Ah, I had forgotten, he exclaimed.",
    "But there was something even more startling than this resemblance.",
    "I have to be careful of them, as they tear very easily.",
    "Of course, that is uninteresting, she continued.",
    "A moment before he was intoxicated by a joy that was almost madness.",
    "Now these things had been struck dead within him.",
    "For an instant he saw Pierre drawn like a silhouette against the sky.",
    "Goodbye, Pierre, he shouted.",
    "And MacDougall was beyond the trail, with three weeks to spare.",
    "Philip thrust himself against it and entered.",
    "MacDougall tapped his forehead suspiciously with a stubby forefinger.",
    "He was smooth-shaven, and his hair and eyes were black.",
    "Won't you draw up, gentlemen.",
    "A strange fire burned in his eyes when Thorpe turned.",
    "He had worshiped her, as Dante might have worshiped Beatrice.",
    "Does that look good.",
    "They look as though he had been drumming a piano all his life.",
    "You want to go over and see his gang throw dirt.",
    "Take away their foreman and they wouldn't be worth their grub.",
    "That's the sub-foreman, explained Thorpe.",
    "Philip made no effort to follow.",
    "He came first a year ago, and revealed himself to Jeanne.",
    "They are to attack your camp tomorrow night.",
    "Two days ago Jeanne learned where her father's men were hiding.",
    "I was near the cabin, and saw you.",
    "Low bush whipped him in the face and left no sting.",
    "Suddenly Jeanne stopped for an instant.",
    "There was none of the joy of meeting in his face.",
    "And when you come back in a few days, bring Eileen.",
    "Gregson had left the outer door slightly ajar.",
    "The date was nearly eighteen years old.",
    "They were the presage of storm.",
    "Down there the earth was already swelling with life.",
    "For the first time in his life he was yearning for a scrap.",
    "She had been thoroughly and efficiently mauled.",
    "Every bone in her aged body seemed broken or dislocated.",
    "Tomorrow I'm going after that bear, he said.",
    "If not, let's say our prayers and go to bed.",
    "So cheer up, and give us your paw.",
    "This time he did not yap for mercy.",
    "And the air was growing chilly.",
    "Don't you see, I'm chewing this thing in two.",
    "The questions may have come vaguely in his mind.",
    "Like a flash he launched himself into the feathered mass of the owl.",
    "Ahead of them they saw a glimmer of sunshine.",
    "Two gigantic owls were tearing at the carcass.",
    "The big-eyed, clucking moose-birds were most annoying.",
    "Next to them the Canada jays were most persistent.",
    "For a time the exciting thrill of his adventure was gone.",
    "He did not rush in.",
    "It was edged with ice.",
    "He drank of the water cautiously.",
    "But a strange thing happened.",
    "He began to follow the footprints of the dog.",
    "Such a dog the wise driver kills, or turns loose.",
    "Sometimes her dreams were filled with visions.",
    "Thus had the raw wilderness prepared him for this day.",
    "He leapt again, and the club caught him once more.",
    "He cried, and swung the club wildly.",
    "She turned, fearing that Jacques might see what was in her face.",
    "They were following the shore of a lake.",
    "The wolf-dog thrust his gaunt muzzle toward him.",
    "From now on we're pals.",
    "He says he bought him of Jacques Le Beau.",
    "How much was it.",
    "Youth had come back to her, freed from the yoke of oppression.",
    "It was not a large lake, and almost round.",
    "Its diameter was not more than two hundred yards.",
    "It drowned all sound that brute agony and death may have made.",
    "Fresh cases, still able to walk, they clustered about the spokesman.",
    "Between him and the beach was the cane-grass fence of the compound.",
    "Besides, he was paid one case of tobacco per head.",
    "They die out of spite.",
    "The other felt a sudden wave of irritation rush through him.",
    "Oppressive as the heat had been, it was now even more oppressive.",
    "The ringing of the big bell aroused him.",
    "At first he puzzled over something untoward he was sure had happened.",
    "A dead man is of no use on a plantation.",
    "I don't know why you're here at all.",
    "What part of the United States is your home.",
    "My, I'm almost homesick for it already.",
    "She nodded, and her eyes grew soft and moist.",
    "I was brought up the way most girls in Hawaii are brought up.",
    "That came before my A B C's.",
    "It was the same way with our revolvers and rifles.",
    "But it contributed to the smash.",
    "The last one I knew was an overseer.",
    "Do you know any good land around here.",
    "The Resident Commissioner is away in Australia.",
    "I cannot follow you, she said.",
    "I never allow what can't be changed to annoy me.",
    "Why, the average review is more nauseating than cod liver oil.",
    "His voice was passionately rebellious.",
    "Don't you see I hate you.",
    "So Hughie and I did the managing ourselves.",
    "It happened to him at the Gallina Society in Oakland one afternoon.",
    "He cried in such genuine dismay that she broke into hearty laughter.",
    "Wash your hands of me.",
    "I think it's much nicer to quarrel.",
    "I saw it when she rolled.",
    "I only read the quotations.",
    "He was the soul of devotion to his employers.",
    "Out of his eighteen hundred, he laid aside sixteen hundred each year.",
    "You have heard always how he was the lover of the Princess Naomi.",
    "They ought to pass here some time today.",
    "I had been sad too long already.",
    "All eyes, however, were staring at him in certitude of expectancy.",
    "He had observed the business life of Hawaii and developed a vaulting ambition.",
    "I may manage to freight a cargo back as well.",
    "O'Brien had been a clean living young man with ideals.",
    "He it was that lived to found the family of the Patino.",
    "Straight out they swam, their heads growing smaller and smaller.",
    "You won't die of malnutrition, be sure of that.",
    "See the length of the body and that elongated neck.",
    "They are coming ashore, whoever they are.",
    "Soaked in seawater they offset the heat rays.",
    "Think of investing in such an adventure.",
    "Nobody knew his history, they of the Junta least of all.",
    "I have been doubly baptized.",
    "They wouldn't be sweeping a big vessel like the Martha.",
    "Joan looked triumphantly at Sheldon, who bowed.",
    "And I hope you've got plenty of chain out, Captain Young.",
    "The discovery seemed to have been made on the spur of the moment.",
    "They handled two men already, both grub-thieves.",
    "Eli Harding asked, as Shunk started to follow.",
    "Now go ahead and tell me in a straightforward way what has happened.",
    "That's where they cut off the Scottish Chiefs and killed all hands.",
    "And after the bath a shave would not be bad.",
    "Now please give a plain statement of what occurred.",
    "You can take a vacation on pay.",
    "They are big trees and require plenty of room.",
    "And Raoul listened again to the tale of the house.",
    "There are no kiddies and half grown youths among them.",
    "Oolong Atoll was one hundred and forty miles in circumference.",
    "McCoy found a stifling, poisonous atmosphere in the pent cabin.",
    "It would give me nervous prostration.",
    "She said with chattering teeth.",
    "I'll be out of my head in fifteen minutes.",
    "I do not blame you for anything; remember that.",
    "If you mean to insinuate -- Brentwood began hotly.",
    "The woman in you is only incidental, accidental, and irrelevant.",
    "There was no forecasting this strange girl's processes.",
    "But what they want with your toothbrush is more than I can imagine.",
    "Give them their choice between a fine or an official whipping.",
    "Keep an eye on him.",
    "Those are my oysters, he said at last.",
    "They are not regular oyster pirates, Nicholas continued.",
    "One by one the boys were captured.",
    "The weeks had gone by, and no overt acts had been attempted.",
    "Here, in the midmorning, the first casualty occurred.",
    "They were deep in the primeval forest.",
    "He had been foiled in his attempt to escape.",
    "And twenty men could hold it with spears and arrows.",
    "Bassett was a fastidious man.",
    "There's a big English general right now whose name is Roberts.",
    "This tacit promise of continued acquaintance gave Saxon a little joy-thrill.",
    "I tell you I am disgusted with this adventure tomfoolery and rot.",
    "From my earliest recollection my sleep was a period of terror.",
    "But all my dreams violated this law.",
    "It is very plausible to such people, a most convincing hypothesis.",
    "But they make the mistake of ignoring their own duality.",
    "I graduated last of my class.",
    "They had no fixed values, to be altered by adjectives and adverbs.",
    "He was pressing beyond the limits of his vocabulary.",
    "Very early in my life, I separated from my mother.",
    "His infernal chattering worries me even now as I think of it.",
    "White Leghorns, said Mrs Mortimer.",
    "Massage under tension, was the cryptic reply.",
    "Therefore, hurrah for the game.",
    "It lived in perpetual apprehension of that quarter of the compass.",
    "Broken-Tooth yelled with fright and pain.",
    "Thus was momentum gained in the Younger World.",
    "Saxon waited, for she knew a fresh idea had struck Billy.",
    "We had been chased by them ourselves, more than once.",
    "He was a wise hyena.",
    "Production is doubling and quadrupling upon itself.",
    "And the Edinburgh Evening News says, with editorial gloom.",
    "With my strength I slammed it full into Red-Eye's face.",
    "The log on which Lop-Ear was lying got adrift.",
    "This is a common experience with all of us.",
    "He considered the victory already his and stepped forward to the meat.",
    "It was not Red-Eye's way to forego revenge so easily.",
    "Whiz-zip-bang. Lop-Ear screamed with sudden anguish.",
    "Cherokee identified himself with his instinct.",
    "They were less stooped than we, less springy in their movements.",
    "The Fire People, like ourselves, lived in caves.",
    "Ah, indeed.",
    "Red-Eye never committed a more outrageous deed.",
    "Poor little Crooked-Leg was terribly scared.",
    "Unconsciously, our yells and exclamations yielded to this rhythm.",
    "This is no place for you.",
    "He'll knock you off a few sticks in no time.",
    "Red-Eye swung back and forth on the branch farther down.",
    "So unexpected was my charge that I knocked him off his feet.",
    "Encouraged by my conduct, Big-Face became a sudden ally.",
    "The fighting had now become intermittent.",
    "They obeyed him, and went here and there at his commands.",
    "It was like the beating of hoofs.",
    "Why, doggone you all, shake again.",
    "Seventeen, no, eighteen days ago.",
    "You mean for this State, General, Alberta.",
    "He seemed to fill it with his tremendous vitality.",
    "She was trying to pass the apron string around him.",
    "Get down and dig in.",
    "They are greatly delighted with anything that is bright or giveth a sound.",
    "They only lifted seven hundred and fifty.",
    "It was simple, in its way, and no virtue of his.",
    "Is that Pat Hanrahan's mug looking hungry and willing.",
    "It was more like sugar.",
    "I'm sure going along with you all, Elijah.",
    "Here the explosion of mirth drowned him out.",
    "Fresh meat they failed to obtain.",
    "A burst of laughter was his reward.",
    "You don't catch me at any such foolishness.",
    "A month passed by, and Bonanza Creek remained quiet.",
    "They continued valiantly to lie, but the truth continued to outrun them.",
    "Earth and gravel seemed to fill the pan.",
    "But he no longer cared quite so much for that form of diversion.",
    "But he did not broach it, preferring to mature it carefully.",
    "Nope, not the slightest idea.",
    "It is not an attempt to smash the market.",
    "We have plenty of capital ourselves, and yet we want more.",
    "These rumors may even originate with us.",
    "A wildly exciting time was his during the week preceding Thursday the eighteenth.",
    "There is not an iota of truth in it, certainly not.",
    "I just do appreciate it without being able to express my feelings.",
    "In partnership with Daylight, the pair raided the San Jose Interurban.",
    "He saw all men in the business game doing this.",
    "It issued a rate of forty two dollars a car on charcoal.",
    "He saw only the effect in a general, sketchy way.",
    "Points of view, new ideas, life.",
    "But life's worth more than cash, she argued.",
    "The butchers and meat cutters refused to handle meat destined for unfair restaurants.",
    "Your price, my son, is just about thirty per week.",
    "This sound did not disturb the hush and awe of the place.",
    "That's why its boundaries are all gouged and jagged.",
    "How old are you, daddy.",
    "But in the canyons water was plentiful and also a luxuriant forest growth.",
    "My name's Ferguson.",
    "Daylight found himself charmed and made curious by the little man.",
    "To his surprise, her answer was flat and uncompromising.",
    "The farmer works the soil and produces grain.",
    "That's what Carnegie did.",
    "I can't argue with you, and you know that.",
    "Bob, growing disgusted, turned back suddenly and attempted to pass Mab.",
    "It was my idea to a tee.",
    "Mab, she said.",
    "I'll go over tomorrow afternoon.",
    "But he reconciled himself to it by an act of faith.",
    "There is that magnificent Bob, eating his head off in the stable.",
    "Already he had begun borrowing from the banks.",
    "It's the strap hangers that'll keep us from going under.",
    "As for himself, weren't the street railway earnings increasing steadily.",
    "A rising tide of fat had submerged them.",
    "Call me that again, he murmured ecstatically.",
    "In the car were Unwin and Harrison, while Jones sat with the chauffeur.",
    "And here's another idea.",
    "Manuel had one besetting sin.",
    "The man smiled grimly, and brought a hatchet and a club.",
    "Curly rushed her antagonist, who struck again and leaped aside.",
    "His newborn cunning gave him poise and control.",
    "Perrault found one with head buried in the grub box.",
    "It seemed the ordained order of things that dogs should work.",
    "And that was the last of Francois and Perrault.",
    "Mercedes screamed, cried, laughed, and manifested the chaotic abandonment of hysteria.",
    "The Eldorado emptied its occupants into the street to see the test.",
    "He could feel a new stir in the land.",
    "So we have to fit the boat throughout with oil lamps as well.",
    "It will break our hearts and our backs to hoist anchor by hand.",
    "There is another virtue in these bulkheads.",
    "But I am at the end of my resources.",
    "Now our figuring was all right.",
    "It lasted as a deterrent for two days.",
    "The added weight had a velocity of fifteen miles per hour.",
    "It is also an insidious, deceitful sun.",
    "The Portuguese boy crawled nearer and nearer.",
    "The Portuguese boy passed the Hawaiian.",
    "When I came to I was waving my hat and murmuring ecstatically.",
    "By golly, the boy wins.",
    "Halfway around the track one donkey got into an argument with its rider.",
    "McVeigh when he returns from a trip to Honolulu.",
    "Obviously, it was a disease that could be contracted by contact.",
    "Otherwise no restriction is put upon their seafaring.",
    "They do not know the length of time of incubation.",
    "Enters now the psychology of the situation.",
    "It was not exactly a deportation.",
    "Quick was the disappointment in his face, yet smiling was the acquiescence.",
    "Nevertheless we found ourselves once more in the high seat of abundance.",
    "Wada and Nakata were in a bit of a funk.",
    "The boy at the wheel lost his head.",
    "To her the bridge was tambo, which is the native for taboo.",
    "A half a case of tobacco was worth three pounds.",
    "What do you mean by this outrageous conduct.",
    "But Martin smiled a superior smile.",
    "By that answer my professional medical prestige stood or fell.",
    "At sea, Monday, March 16, 1908.",
    "At sea, Wednesday, March 18, 1908.",
    "Yes, sir, I corrected.",
    "Violent life and athletic sports had never appealed to me.",
    "You live on an income which your father earned.",
    "He was worth nothing to the world.",
    "Then you don't believe in altruism.",
    "The creative joy, I murmured.",
    "He deluged me, overwhelmed me with argument.",
    "Ah, it is growing dark and darker.",
    "I was Hump, cabin boy on the schooner Ghost.",
    "A sinewy hand, dripping with water, was clutching the rail.",
    "No man ate of the seal meat or the oil.",
    "I noticed blood spouting from Kerfoot's left hand.",
    "Three oilers and a fourth engineer, was his greeting.",
    "Eighteen hundred, he calculated.",
    "The sharp voice of Wolf Larsen aroused me.",
    "I obeyed, and a minute or two later they stood before him.",
    "But it won't continue, she said with easy confidence.",
    "What I saw I could not at first believe.",
    "The stout wood was crushed like an eggshell.",
    "There's too much of the schoolboy in me.",
    "I had forgotten their existence.",
    "Ah, we were very close together in that moment.",
    "But she swung obediently on her heel into the wind.",
    "They are his tongue, by which he makes his knowledge articulate.",
    "Between the rush of the cascades, streaks of rust showed everywhere.",
    "He'll never do a tap of work the whole Voyage.",
    "Captain West may be a Samurai, but he is also human.",
    "And so early in the voyage, too.",
    "In the matter of curry she is a sheer genius.",
    "The eastern heavens were equally spectacular.",
    "He spat it out like so much venom.",
    "I saw Mr Pike nod his head grimly and sarcastically.",
    "He is too keenly intelligent, too sharply sensitive, successfully to endure.",
    "The night was calm and snowy.",
    "I sailed third mate in the little Vampire before you were born.",
    "His outstretched arm dropped to his side, and he paused.",
    "At this moment I felt a stir at my shoulder.",
    "Wada, Louis, and the steward are servants of Asiatic breed.",
    "Also, she has forbidden them smoking their pipes in the after-room.",
    "I tried to read George Moore last night, and was dreadfully bored.",
    "Tom Spink has a harpoon.",
    "Nimrod replied, with a slight manifestation of sensitiveness.",
    "And their chief virtue lies in that they will never wear out.",
    "Beyond dispute, Corry Hutchinson had married Mabel Holmes.",
    "No-sir-ee.",
    "Each insult added to the value of the claim.",
    "For the rest, he was a mere automaton.",
    "The river bared its bosom, and snorting steamboats challenged the wilderness.",
    "Their love burned with increasing brightness.",
    "They were artists, not biologists.",
    "Both Johnny and his mother shuffled their feet as they walked.",
    "And as in denial of guilt, the one-legged boy replied.",
    "Burnt out like the crater of a volcano.",
    "The boy, O'Brien, was specially maltreated.",
    "O'Brien took off his coat and bared his right arm.",
    "He bore no grudges and had few enemies.",
    "And Tom King patiently endured.",
    "King took every advantage he knew.",
    "The lines were now very taut.",
    "And right there I saw and knew it all.",
    "Who the devil gave it to you to be judge and jury.",
    "You're joking me, sir, the other managed to articulate.",
    "Anything unusual or abnormal was sufficient to send a fellow to Molokai.",
    "His beady black eyes saw bargains where other men saw bankruptcy.",
    "He was an athlete and a giant.",
    "We fished sharks on Niihau together.",
    "The Claudine was leaving next morning for Honolulu.",
    "In short, my joyous individualism was dominated by the orthodox bourgeois ethics.",
    "Soon shall it be thrust back from off prostrate humanity.",
    "Yet, in accordance with Ernest's test of truth, it worked.",
    "Much more Ernest told them of themselves and of his disillusionment.",
    "There is more behind this than a mere university ideal.",
    "No, it is a palace, wherein there are many servants.",
    "We must give ourselves and not our money alone.",
    "We are consumed in our own flesh-pots.",
    "But here amongst ourselves let us speak out.",
    "Also, there was awe in their faces.",
    "Out of abstractions Ernest had conjured a vision and made them see it.",
    "Illuminating oil was becoming all profit.",
    "Such an act was in direct violation of the laws of the land.",
    "He was fond of quoting a fragment from a certain poem.",
    "Without them he could not run his empire.",
    "For such countries nothing remained but reorganization.",
    "They could not continue their method of producing surpluses.",
    "At once would be instituted a dozen cooperative commonwealth states.",
    "The Oligarchy wanted violence, and it set its agents provocateurs to work.",
    "Nowhere did the raw earth appear.",
    "The lush vegetation of that sheltered spot make a natural shield.",
    "Men who endure it, call it living death.",
    "As I say, he had tapped the message very rapidly.",
    "Ask him, I laughed, then turned to Pasquini.",
    "In what bucolic school of fence he had been taught was beyond imagining.",
    "May drought destroy your crops.",
    "Dunham, can your boy go along with Jesse.",
    "But Johannes could, and did.",
    "A new preacher and a new doctrine come to Jerusalem.",
    "He would destroy all things that are fixed.",
    "He was an enthusiast and a desert dweller.",
    "What Pascal glimpsed with the vision of a seer, I have lived.",
    "I should like to engage just for one whole life in that.",
    "Yea, so are all the lesser animals of today clean.",
    "The Warden with a quart of champagne.",
    "Without a doubt, some of them have dinner engagements.",
    "I had been born with no organic, chemical predisposition toward alcohol.",
    "He may anticipate the day of his death.",
    "The Italian rancho was a bachelor establishment.",
    "I lost my balance and pitched head foremost into the ooze.",
    "Men like Joe Goose dated existence from drunk to drunk.",
    "Also, churches and preachers I had never known.",
    "Do you know that we weigh every pound of coal we burn.",
    "This also became part of the daily schedule.",
    "All an appearance can know is mirage.",
    "Yet he dreams he is immortal, I argue feebly.",
    "I am writing these lines in Honolulu, Hawaii.",
    "Jack London, Waikiki Beach, Honolulu, Oahu.",
    "Jerry was so secure in his nook that he did not roll away.",
    "Why, he's bought forty pounds of goods from you already.",
    "The last refugee had passed.",
    "And the foundation stone of service, in his case, was obedience.",
    "Peace be unto you and grace before the Lord.",
    "His mouth opened; words shaped vainly on his lips.",
    "Bill lingered, contemplating his work with artistic appreciation.",
    "What the flaming.",
    "Mrs McFee's jaws brought together with a snap.",
    "Then it is as I said, Womble announced with finality.",
    "With them were Indians, also three other men.",
    "Dennin's hands were released long enough for him to sign the document.",
    "Now Irvine was a man of impulse, a poet.",
    "He was just bursting with joy, joy over what.",
    "At Lake Linderman I had one canoe, very good Peterborough canoe.",
    "Behind him lay the thousand-years-long road across all Siberia and Russia.",
    "He had forgotten to build a fire and thaw out.",
    "I never saw anything like her in my life.",
    "There was no law on the Yukon save what they made for themselves.",
    "Good business man, Curly, O'Brien was saying.",
    "There weren't any missions, and he was the man to know.",
    "And the big Persian knew of his existence before he did of hers.",
    "Once the jews harp began emitting its barbaric rhythms, Michael was helpless.",
    "But we'll just postpone this.",
    "There was the Emma Louisa.",
    "This is my fifth voyage.",
    "It was this proposition that started the big idea in Daughtry's mind.",
    "Daughtry elaborated on the counting trick by bringing Cocky along.",
    "Enjoy it he did, but principally for Steward's sake.",
    "I have long noted your thirst unquenchable.",
    "Wonder if he's a lion dog, Charles suggested.",
    "We don't see ourselves as foolish.",
    "He had comparatively no advantages at first.",
    "He had proved it today, with his amateurish and sophomoric productions.",
    "I was sick once -- typhoid.",
    "In a way he is my protege.",
    "We are both children together.",
    "It's only his indigestion I find fault with.",
    "She'd make a good wife for the cashier.",
    "Gad, do I remember it.",
    "You got out by fighting, and I through a pretty girl.",
    "I can see that knife now.",
    "When I can't see beauty in woman I want to die.",
    "His slim fingers closed like steel about Philip's.",
    "He seized Gregson by the arm and led him to the door.",
    "Hear the Indian dogs wailing down at Churchill.",
    "Burke himself had criticized it because of the smile.",
    "I'd say there was going to be a glorious scrap.",
    "He turned the map to Gregson, pointing with his finger.",
    "His eyes never took themselves for an instant from his companion's face.",
    "Something that Whittemore had not yet said thrilled him.",
    "Lakes and rivers, hundreds of them, thousands of them.",
    "Whitefish, Gregson, whitefish and trout.",
    "They robbed me a few years later.",
    "He chuckled as he pulled out his pipe and began filling it.",
    "Everything was working smoothly, better than I had expected.",
    "I was completely lost in my work.",
    "His slim hands gripped the edges of the table.",
    "He made no reply as he waited for Whittemore to continue.",
    "Philip dropped back into his chair.",
    "If I was out of the game it would be easily made.",
    "MacDougall, my engineer, believes it.",
    "It is growing, every day, every hour.",
    "Now, you understand.",
    "You have associated with some of these men.",
    "And there's no chivalry, no quarter shown in this fight.",
    "Lord Fitzhugh is the key to the whole situation.",
    "All operations have been carried on from Montreal and Toronto.",
    "Gregson held a lighted match until it burnt his fingertips.",
    "Gregson had seated himself under the lamp and was sharpening a pencil.",
    "He caught himself with a jerk.",
    "How does your wager look now.",
    "He confessed that the sketch had startled him.",
    "After all, the picture was only a resemblance.",
    "He wondered, too, where Roscoe was.",
    "Philip knew that she was not an Indian.",
    "In her haste to get away she had forgotten these things.",
    "Philip took a step toward Gregson, half determined to awaken him.",
    "The thought set his blood tingling.",
    "But if Pierre did not return, until tomorrow.",
    "Ten minutes had not elapsed since he had dropped the handkerchief.",
    "It won't be for sale.",
    "For a few moments he ate in silence.",
    "Philip did not pursue the subject.",
    "Philip produced a couple of cigars and took a chair opposite him.",
    "Suppose you saw me at work through the window.",
    "He looked like one who had passed through an uncomfortable hour or two.",
    "There was nothing more, except a large ink blot under the words.",
    "All this day Gregson remained in the cabin.",
    "The sixth day he spent in the cabin with Gregson.",
    "The flush was gone from her face.",
    "That is why I am, am rattled, he laughed.",
    "He understood the meaning of the look.",
    "She was even more beautiful than when I saw her, before.",
    "I'll give a thousand if you produce her, retorted Gregson.",
    "They have won popular sentiment through the newspapers.",
    "We must achieve our own salvation.",
    "In moments of mental energy Philip was restless.",
    "He would keep his faith with Gregson for the promised day or two.",
    "Something about it seemed to fascinate him, to challenge his presence.",
    "Now it was missing from the wall.",
    "He boiled himself some coffee and sat down to wait.",
    "I'm going down there with you, and I'm going to fight.",
    "Now have you got anything to say against me, Mr Philip.",
    "If I meet her again I shall apologize, said Eileen.",
    "Below him the shadow was broken into a pool of rippling starlight.",
    "Only the chance sound had led him to observe them.",
    "Could the incident have anything to do with Jeanne and Pierre.",
    "There was no chance to fire without hitting him.",
    "There was no answer from the other side.",
    "Then he hastened on, as Pierre had guided him.",
    "With these arguments he convinced himself that he should go on alone.",
    "Yet, behind them there was another and more powerful motive.",
    "In that case he could not miss them, if he used caution.",
    "Before Philip could recover himself Jeanne's startled guards were upon him.",
    "It is the nearest refuge.",
    "There was pride and strength, the ring of triumph in his voice.",
    "The truth of it set Jeanne quivering.",
    "Tomorrow it will be strong enough for you to stand upon.",
    "You were going to leave after you saw me on the rock.",
    "He bit his tongue, and cursed himself at this fresh break.",
    "In it there was something that was almost tragedy.",
    "Your face is red with blood.",
    "Her eyes smiled truth at him as he came up the bank.",
    "He can care for himself.",
    "They will search for us between their camp and Churchill.",
    "Until I die, he exclaimed.",
    "Her beautiful hair was done up in shining coils.",
    "The Churchill narrowed and its current became swifter as they progressed.",
    "For a full half minute Jeanne looked at him without speaking.",
    "I want to die in it.",
    "Darkness hid him from Jeanne.",
    "And yet if she came he had no words to say.",
    "He heard a sound which brought him quickly into consciousness of day.",
    "Within himself he called it no longer his own.",
    "Besides, that noise makes me deaf.",
    "Philip looked back from the crest and saw Jeanne leaning over the canoe.",
    "Fifty yards ahead of her were the first of the rocks.",
    "There was one chance, and only one, of saving Jeanne.",
    "You're a devil for fighting, and will surely win.",
    "I'll only be in the way.",
    "He lifted his eyes, and a strange cry burst from his lips.",
    "Shooting pains passed like flashes of electricity through his body.",
    "I know that you are in charge there, and Jeanne knows.",
    "For a full minute the two men stared into each other's face.",
    "He was sure, now, of but few things.",
    "It was a miracle, and I owe you my life.",
    "Philip ate lightly of the food which Pierre had ready for him.",
    "Such men believe, when they come together.",
    "The journey was continued at dawn.",
    "Jeanne and Pierre both gazed toward the great rock.",
    "There was something pathetic in the girl's attitude now.",
    "He moved his position, and the illusion was gone.",
    "For two hours not a word passed between them.",
    "I have hunted along this ridge, replied Philip.",
    "That's Thorpe's, said the young engineer.",
    "We saw your light, and thought you wouldn't mind a call.",
    "Billinger may arrive in time.",
    "There's the hitch, replied Thorpe, rolling a cigarette.",
    "I want my men to work by themselves.",
    "Philip saw MacDougall soon after his short talk with Thorpe.",
    "Neither could they understand the growing disaffection among Thorpe's men.",
    "Two weeks passed, and in that time Thorpe left camp three times.",
    "It was the third or fourth time that Philip had heard MacDougall swear.",
    "Blood was oozing slowly from the wounded man's right breast.",
    "He destroyed everything that had belonged to the woman.",
    "Philip bent low over Pierre.",
    "Did Thorpe go to see any one in Churchill.",
    "She saw the answer in his face.",
    "Thorpe and his men were to destroy this camp, and kill you.",
    "There is no need of further detail, now -- for you can understand.",
    "There followed a roar that shook the earth.",
    "Blind with rage, he darted in.",
    "In it was the joy of life.",
    "Swiftly his eyes measured the situation.",
    "But this little defect did not worry him.",
    "And then, steadily, he began to chew.",
    "Together they ate the rabbit.",
    "They edged nearer, and stood shoulder to shoulder facing their world.",
    "It was beating and waiting in the ambush of those black pits.",
    "Something vastly more thrilling had come into it now.",
    "It took him half an hour to reach the edge of it.",
    "But there was no longer the mother yearning in his heart.",
    "Besides, had he not whipped the big owl in the forest.",
    "After all, it was simply a mistake in judgment.",
    "Had it struck squarely it would have killed him.",
    "The Indian even poked his stick into the thick ground spruce.",
    "Pebbles and dirt flew along with hair and fur.",
    "And he was filled with a strange and foreboding fear.",
    "It was steel, a fisher trap.",
    "OW, a wild dog, he growled.",
    "He was a pariah; a wanderer without a friend or a home.",
    "That is the strange part of it.",
    "His freshly caught furs he flung to the floor.",
    "For that reason Le Beau had chosen him to fight the big fight.",
    "In the crib the baby sat up and began to prattle.",
    "She obeyed, shrinking back with the baby in her arms.",
    "His teeth shut with a last click.",
    "It was over when he made his way through the ring of spectators.",
    "In a flash he was on his feet, facing him.",
    "He thought he saw a shudder pass through the Factor's shoulders.",
    "The moon had already begun its westward decline.",
    "They laughed like two happy children.",
    "He pulled, and the log crashed down to break his back.",
    "Fast, but endure.",
    "A little before dawn of the day following, the fire relief came.",
    "The Indian felt the worship of her warm in his heart.",
    "He drew in a deep breath as he looked at them.",
    "Then he shouted, Shut up.",
    "He changed his seat for a steamer reclining chair.",
    "On the far corner of the compound fence a hawk brooded.",
    "To these he gave castor oil.",
    "Hatred and murder and lust for revenge they possessed to overflowing.",
    "Sheldon glanced at the thermometer.",
    "I'll see to poor Hughie.",
    "Her gray eyes were flashing, and her lips were quivering.",
    "Also, I want information.",
    "Let them go out and eat with my boys.",
    "I, I beg pardon, he drawled.",
    "And you preferred a cannibal isle and a cartridge belt.",
    "I was in New York when the crash came.",
    "No, I did not fall among thieves.",
    "Such things in her brain were like so many oaths on her lips.",
    "Your being wrecked here has been a godsend to me.",
    "I can't go elsewhere, by your own account.",
    "Her achievements with cocoanuts were a revelation.",
    "He glanced down at her helplessly, and moistened his lips.",
    "That is what distinguishes all of us from the lower animals.",
    "Idealism led him to philosophic anarchy, and his family threw him off.",
    "He also contended that better confidence was established by carrying no weapons.",
    "Outsiders are allowed five minute speeches, the sick man urged.",
    "So was Packard's finish suicide.",
    "Joan cried, with shining eyes.",
    "Nobody knows how the natives got them.",
    "How can you manage all alone, Mr Young.",
    "The planters are already considering the matter.",
    "I use great trouble advisedly.",
    "Dear Sir, Your second victim has fallen on schedule time.",
    "We leave the eventuality to time and law.",
    "I also understand that similar branch organizations have made their appearance in Europe.",
    "Society is shaken to its foundations.",
    "A month in Australia would finish me.",
    "Down through the perfume weighted air fluttered the snowy fluffs of the cottonwoods.",
    "You were destroying my life.",
    "Horses and rifles had been her toys, camp and trail her nursery.",
    "I'm as good as a man, she urged.",
    "You read the quotations in today's paper.",
    "He's terribly touchy about his black wards, as he calls them.",
    "Whatever he guessed he locked away in the taboo room of Naomi.",
    "This is eighteen eighty.",
    "Death is and has been ever since old Maui died.",
    "Some boy, she laughed acquiescence.",
    "Let us talk it over and find a way out.",
    "It is a good property, and worth more than that.",
    "I wish you were more adaptable, Joan retorted.",
    "Such is my passage engaged on the steamer.",
    "The issue was not in doubt.",
    "Well, there are better men in Hawaii, that's all.",
    "Harry Bancroft, Dave lied.",
    "It's a Yankee, Joan cried.",
    "He was the leader, and Tudor was his lieutenant.",
    "They likewise are disinclined to being eaten.",
    "But to culture the Revolution thus far had exhausted the Junta.",
    "The President of the United States was his friend.",
    "Your face was the personification of duplicity.",
    "Shorty turned to their employers.",
    "You were engaged.",
    "I saw it all myself, and it was splendid.",
    "Now run along, and tell them to hurry.",
    "What's that grub-thief got to do with it.",
    "It was a superb picture.",
    "So she said, the irate skipper dashed on.",
    "And watch out for wet feet, was his parting advice.",
    "Raoul yelled, in order to make himself heard.",
    "Oolong was two hundred and fifty miles from the nearest land.",
    "They just lay off in the bush and plugged away.",
    "The very thought of the effort to swim over was nauseating.",
    "And there was a dog that barked.",
    "There are four, all low, McCoy answered.",
    "The women they carried away with them to the Big Valley.",
    "The Japanese understood as we could never school ourselves or hope to understand.",
    "They had been on the same lay as ourselves.",
    "You are positively soulless, he said savagely.",
    "Harrison is still my chauffeur.",
    "The boy grew and prospered.",
    "He wanted to give the finish to this foe already so far gone.",
    "Exciting times are the lot of the fish patrol.",
    "I know they are my oysters.",
    "By this time Charley was as enraged as the Greek.",
    "They must have been swept away by the chaotic currents.",
    "It resembled tea less than lager beer resembles champagne.",
    "The very opposite is true; they are discouraged vagabonds.",
    "At the same time spears and arrows began to fall among the invaders.",
    "Then, again, Tudor had such an irritating way about him.",
    "Outwardly, he maintained a calm and smiling aspect.",
    "Tudor surveyed him with withering disgust.",
    "You fired me out of your house, in short.",
    "Her mouth opened, but instead of speaking she drew a long sigh.",
    "It's worth eight dollars.",
    "And he did hurt my arm.",
    "Saxon's onto her job.",
    "Only once did I confide the strangeness of it all to another.",
    "But this time it was Saxon who rebelled.",
    "I was not to cry out in the face of fear.",
    "And now put yourself in my place for a moment.",
    "The boy threw back his head with pride.",
    "Saxon nodded, and the boy frowned.",
    "Why not like any railroad station or ferry depot.",
    "We could throw stones with our feet.",
    "It was put together in a casual, helter-skelter sort of way.",
    "These were merely stout sticks an inch or so in diameter.",
    "Then it was that a strange thing happened.",
    "From the source of light a harsh voice said.",
    "But I did not enjoy it long.",
    "We were now good friends.",
    "Two of the Folk were already up.",
    "Now animals do not like mockery.",
    "He gave one last snarl and slid from view among the trees.",
    "Again the girls applauded, and Mrs Hall cried.",
    "Just the same I'd sooner be myself than have book indigestion.",
    "Some of the smaller veins had doubtless been ruptured.",
    "But we were without this momentum.",
    "There was one difficulty, however.",
    "The hyena proceeded to dine.",
    "The time was considered auspicious.",
    "Or have they already devised one.",
    "We would not spend another such night.",
    "At first his progress was slow and erratic.",
    "He placed his paw on one, and its movements were accelerated.",
    "The awe of man rushed over him again.",
    "The Fire-Men wore animal skins around their waists and across their shoulders.",
    "Between him and all domestic animals there must be no hostilities.",
    "For a much longer time Lop-Ear and I remained and watched.",
    "All right, Sir, replied Jock with great regret.",
    "At times I wondered where Sir Archibald got his style.",
    "Why should a fellow throw up the sponge after the first round.",
    "His hand shot out and clutched Crooked-Leg by the neck.",
    "Miss Brodie's smile was slightly sarcastic.",
    "Does the old boy often go off at half-cock that way.",
    "A flying arrow passed between us.",
    "I pulled, suddenly, with all my might.",
    "Here we allow our solicitors to look after our legal work.",
    "His previous wives had never lived long enough to bear him children.",
    "It was our river emerging like ourselves from the great swamp.",
    "Cameron looked at his hands with their long, sinewy fingers.",
    "We got few vegetables and fruits, and became fish eaters.",
    "We never made another migration.",
    "Nor was Elam Harnish an exception.",
    "A little treatment, massage, with some help from the doctor.",
    "The 29th very foggy.",
    "Dig in; you're sure good, was Daylight's answer.",
    "The apron string loomed near and he shied like an unbroken colt.",
    "He had been born with this endowment.",
    "And this was their sole conversation throughout the meal.",
    "Though the aurora still flamed, another day had begun.",
    "He did not believe in the burning of daylight for such a luxury.",
    "Again he had done the big thing.",
    "Daylight was tired, profoundly tired.",
    "The regret in his voice was provocative of a second burst of laughter.",
    "Instead, he arrived on the night of the second day.",
    "Their supply of grub was gone.",
    "Crickets began to chirp, and more geese and ducks flew overhead.",
    "Not till the twentieth of May did the river break.",
    "It was a gigantic inadequacy.",
    "Our Mr Howison will call upon you at your hotel.",
    "He had been so easy.",
    "Change chairs, Daylight commanded.",
    "I'd sooner have my chips back.",
    "They only had a little thirty thousand dollar fire.",
    "His partners had starved and died on the Stewart.",
    "As to how she dressed, he had no ideas at all.",
    "It does, was her audacious answer.",
    "Oh, it's just a novel, a love story.",
    "Whoever lived on the ranch did that.",
    "How old are you, mother.",
    "Here he got a fresh thrill.",
    "It was unobtrusive, yet it was there.",
    "Well, I'll be plumb gosh darned.",
    "These quick little joys of hers were sources of joy to him.",
    "I play that choice wide open to win.",
    "Each improvement makes the value of everything else pump up.",
    "But how are you going to do it.",
    "Lots of men take women buggy riding.",
    "Daylight made no answer, and the door closed behind him.",
    "There's not an iota of truth in it.",
    "But ever his gaze returned to that Crouched Venus on the piano.",
    "Would you be satisfied with that one hundredth part of me.",
    "In such a tumbling of values was no time to sell.",
    "Stand off butcher and baker and all the rest.",
    "Matthewson, who's this bookkeeper, Rogers.",
    "Now just what do you want to know.",
    "I want to know how all this is possible.",
    "It's that much junk.",
    "There was proper division of labor in the work they individually performed.",
    "He loved to play Chinese lottery.",
    "The Law of Club and Fang",
    "The temperature dropped to fifty below zero and remained there the whole trip.",
    "And as never before, he was ready to obey.",
    "This state of mind comes of an undue prominence of the ego.",
    "There are the canals of China, and the Yang-tse River.",
    "We threaten to be of the one mind before the voyage is completed.",
    "She was built primarily to sail.",
    "In the Bohemian Club of San Francisco there are some crack sailors.",
    "My age, in years, is twenty two.",
    "I forgot how easily I had taught myself from the printed page.",
    "Any average young fellow can teach himself in a week.",
    "Please do not think that I already know it all.",
    "You see, we were teaching ourselves.",
    "And now behold the perversity of things.",
    "Yield yourself to the waters that are ripping and tearing at you.",
    "Mr McVeigh told me about him.",
    "Unlike Joshua, he stood in no need of divine assistance.",
    "To say the least, Captain Cook was a rather thorough going empiricist.",
    "Man could not conquer them.",
    "Thought I, and a worthy fool he proved.",
    "A scarlet loincloth completed his costume.",
    "I like to speculate upon the glorious future of man.",
    "Christmas is an easy problem compared with a Polynesian giving-feast.",
    "He had peeled off his shirt and was wildly waving it.",
    "And how would we ever find ourselves.",
    "I defy any man to get a Solomon Island sore in California.",
    "A bush chief had died a natural death.",
    "The skipper's and Nakata's gymnastics served as a translation without words.",
    "Last night he showed all the symptoms of coming down with pneumonia.",
    "My idea was that he would have more influence over the natives.",
    "It is merely the simple superlative.",
    "I made no more overtures.",
    "Among my minor afflictions, I may mention a new and mysterious one.",
    "The voyage was our idea of a good time.",
    "At sea, Tuesday, March 17, 1908.",
    "Yes, sir, he answered, with cheerful alacrity.",
    "I was still weak from my prolonged immersion.",
    "The boy hesitated, then mastered his temper.",
    "I was beneath the water, suffocating and drowning.",
    "The pain from my hurt knee was agonizing.",
    "The hunters were still arguing and roaring like some semi-human amphibious breed.",
    "I have been robbed, sir, I amended.",
    "You were looking squeamish this afternoon, he began.",
    "How could I answer the question on the spur of the moment.",
    "I learned it myself in English ships.",
    "An altruistic act is an act performed for the welfare of others.",
    "Knowing him, I review the old Scandinavian myths with clearer understanding.",
    "Yes, and no, sir, was the slow reply.",
    "And each year something happened, and I did not go.",
    "How in hell did he know it was you in the dark.",
    "Of course much grumbling went on, and little outbursts were continually occurring.",
    "You have all the advantage.",
    "The dirk mentioned by Wolf Larsen rested in its sheath on my hip.",
    "Have you ever earned a dollar by your own labour.",
    "He gave no reason, but his motive was obvious enough.",
    "Ah, it was sweet in my ears.",
    "He may desire to escape pain, or to enjoy pleasure.",
    "It was impossible to hoist sail and claw off that shore.",
    "There was nothing for us but the wide raw ocean.",
    "I arose obediently and went down the beach.",
    "The next thing to watch out for is bed sores.",
    "At that moment I got the impression that she was willowy.",
    "Your father's fifth command, he nodded.",
    "On occasion, on this traverse, the Cape Verde Islands are raised.",
    "She is essentially the life-giving, life-conserving female of the species.",
    "This was when the explosion occurred.",
    "Also, at regular intervals, he would mutter.",
    "It is a very tenable hypothesis, and will bear looking into.",
    "There were orange-green, gold-green, and a copper-green.",
    "The Gabriel voice of the Samurai rang out.",
    "The sunsets grow more bizarre and spectacular off this coast of the Argentine.",
    "The history of our westward-faring race is written in it.",
    "And the Eurasian Chinese-Englishman bowed himself away.",
    "They were babbling and chattering all together.",
    "Too much, he told me, with ominous rolling head.",
    "He is a candidate, rising from the serf class to our class.",
    "We are cooking on the coal stove and on the oil burners.",
    "The steward has just tendered me a respectful bit of advice.",
    "Well, did they eat.",
    "Famine had been my great ally.",
    "Nowhere in the North is the soil so prolific.",
    "They ran the canoe in and climbed the high earth bank.",
    "The land exchanged its austere robes for the garb of a smiling wanton.",
    "There were stir and bustle, new faces, and fresh facts.",
    "And there was Ethel Baird, whom also you must remember.",
    "He had become a man very early in life.",
    "I did not think you would be so early.",
    "He did not know what went on in the minds of his superiors.",
    "Mops, sir, eagerly answered the sailor at the wheel.",
    "Some one had thrust a large sheath-knife into his hand.",
    "O'Brien emitted a shriek that sank swiftly to a gurgling sob.",
    "Sandel would never become a world champion.",
    "Also, she wouldn't walk.",
    "To my dearest and always appreciated friend, I submit myself.",
    "You used to joyride like the very devil.",
    "They saw each other for the first time in Boston.",
    "Isaac Ford, the austere soldier of the Lord, the old hypocrite.",
    "Eighteen, he added.",
    "His reward should have been peace and repose.",
    "He was an amphibian and a mountaineer.",
    "It was sanctification and salvation.",
    "The history of the eighteenth century is written, Ernest prompted.",
    "They are not biologists nor sociologists.",
    "The more his opponents grew excited, the more Ernest deliberately excited them.",
    "By virtue of that power we shall remain in power.",
    "One guess will do, Ernest retorted.",
    "Take my advice and accept the vacation.",
    "I could not agree with Ernest.",
    "But such divergence of opinion would constitute no menace to society.",
    "It is dog eat dog, and you ate them up.",
    "Let us run them for ourselves.",
    "It was introduced by Representative Dick of Ohio.",
    "Very few people knew of the existence of this law.",
    "The very thing, Ernest agreed.",
    "Also a fellow Senator, Chauncey Depew, said.",
    "Ernest saw in the affair the most sinister import.",
    "Then there was the campaign.",
    "He was manifestly distressed by my coming.",
    "Not a wheel moved in his empire.",
    "The reorganization of these countries took the form of revolution.",
    "You're going in for grab sharing.",
    "The Oligarchy will encourage such ambition and the consequent competition.",
    "Violation of this law was made a high misdemeanor and punished accordingly.",
    "Without discussion, it was the agents provocateurs who caused the Peasant Revolt.",
    "The task we set ourselves was threefold.",
    "Many other similar disconcerting omissions will be noticed in the Manuscript.",
    "The flower of the artistic and intellectual world were revolutionists.",
    "This the Iron Heel foresaw and laid its schemes accordingly.",
    "The mob came on, but it could not advance.",
    "But why continue the tirade, for tirade it was.",
    "After all superfluous flesh is gone what is left is stringy and resistant.",
    "Beyond refusing to sell us food, they left us to ourselves.",
    "He was a merry monarch, especially so for an Asiatic.",
    "What an excited whispering and conferring took place.",
    "Jacob Brinker, who was his roadmate, brought the news.",
    "Thus he turned the tenets and jargon of psychology back on me.",
    "You yellow giant thing of the frost.",
    "Never so strange a prophet came up to Jerusalem.",
    "We who have endured so much surely can endure a little more.",
    "I have seen myself that one man contemplated by Pascal's philosophic eye.",
    "One great drawback to farming in California is our long dry summer.",
    "I remembered the red wine of the Italian rancho, and shuddered inwardly.",
    "I said, and dismissed the matter as not worth thinking about.",
    "Then came my boy code.",
    "And wherever I ranged, the way lay along alcohol-drenched roads.",
    "And as we hurried up town, Joe Goose explained.",
    "The scents of strange vegetation blew off the tropic land.",
    "The life there was healthful and athletic, but too juvenile.",
    "How valiantly I went at it that first day.",
    "It would help to tide me along until I got steady employment.",
    "Did I possess too much vitality.",
    "In his anxiety and solicitude and love they did not count.",
    "He had fulfilled his duty and paid properly.",
    "He knew what taboos he was violating.",
    "Do you value your hide.",
    "You should have seen them when they heard me spitting Chinook.",
    "He plodded on for half an hour, when the hallucination arose again.",
    "Tomorrow or next day it might he gone.",
    "But already he had composed himself.",
    "Zilla relaxed her sour mouth long enough to sigh her satisfaction.",
    "Eggshell is not good to eat.",
    "But there was also talk of witchcraft in the village.",
    "Yea, I will tell thee.",
    "Hans hurled himself upon the prostrate man, striking madly with his fists.",
    "And he thought of Oona, and of her words.",
    "Nor would it thaw out his hands and feet.",
    "The Russian music player, the Count, was her obedient slave.",
    "So far as flags were concerned, they were beyond all jurisdiction.",
    "New idea, he volunteered, brand new idea.",
    "Thirty pounds, said the captain with finality.",
    "The very idea of it was preposterous.",
    "Captain Doane's orders were swiftly obeyed.",
    "Come on, Del Mar challenged.",
    "He had a big chimpanzee that was a winner.",
    "I am sure it must have been some adventure.",
    "That Longfellow chap most likely had written countless books of poetry.",
    "His abnormal power of vision made abstractions take on concrete form.",
    "I'll tell you, the librarian said with a brightening face.",
    "He read his fragments aloud.",
    "Typhoid -- did I tell you.",
    "But she had become an automaton.",
    "At the best, they were necessary accessories.",
    "You were making them talk shop, Ruth charged him.",
}
