---@diagnostic disable: undefined-field, undefined-global
local stack = require("speedtyper.stack").new()
local eq = assert.are.same
describe("Stack tests", function()
    before_each(function()
        stack = require("speedtyper.stack").new()
    end)

    it("push/pop/size", function()
        stack:push("test")
        eq(1, stack:size())
        stack:push("test1")
        eq(2, stack:size())
        eq("test1", stack:pop())
        eq(1, stack:size())
        eq("test", stack:pop())
        eq(0, stack:size())
        eq(nil, stack:pop())
    end)

    it("clear", function()
        stack:push("test")
        eq(1, stack:size())
        stack:clear()
        eq(0, stack:size())
    end)
end)
