---@diagnostic disable: undefined-field, undefined-global
local T = require("speedtyper.typo")
local tracker = T.new(0)
local eq = assert.are.same
local normal = vim.cmd.normal

describe("Typo tracker tests", function()
    before_each(function()
        require("plenary.reload").reload_module("speedtyper")
        tracker = T.new(0)
        normal("Gdgg")
    end)
    it("check current character", function()
        -- space to simulate cursor movement (cursor end up one char to the right)
        Util.simulate_input("x ")
        tracker:check_curr_char("x")
        eq(#tracker.typos, 0)

        Util.simulate_keypress("a<backspace>")
        -- space to simulate cursor movement (cursor end up one char to the right)
        Util.simulate_input("a ")
        tracker:check_curr_char("x")
        eq(tracker.typos[1].line, 1)
        eq(tracker.typos[1].col, 2)

        Util.simulate_keypress("a<CR>")
        -- space to simulate cursor movement (cursor end up one char to the right)
        Util.simulate_input("a ")
        tracker:check_curr_char("x")
        eq(tracker.typos[2].line, 2)
        eq(tracker.typos[2].col, 1)
    end)

    it("correct typo", function()
        -- space to simulate cursor movement (cursor end up one char to the right)
        Util.simulate_input("a ")
        tracker:check_curr_char("x")
        eq(#tracker.typos, 1)

        normal("Gdgg")
        -- space to simulate cursor movement (cursor end up one char to the right)
        Util.simulate_input("x ")
        tracker:check_curr_char("x")
        eq(#tracker.typos, 0)
    end)
end)
