local eq = assert.are.same

describe("Stack tests", function()
    local stack = require("speedtyper.stack")
    local s = stack.new()

    before_each(function()
        s = stack.new()
    end)

    it("push", function()
        s:push(1)
        eq(1, s:size())
        eq({ 1 }, s:get_table())
        s:push(2)
        eq(2, s:size())
        eq({ 1, 2 }, s:get_table())
    end)

    it("pop", function()
        s:push(1)
        s:push(2)
        s:push(3)
        s:push(4)
        s:pop()
        eq(3, s:size())
        eq({ 1, 2, 3 }, s:get_table())
        s:pop_n(2)
        eq(1, s:size())
        eq({ 1 }, s:get_table())
    end)

    it("clear", function()
        s:push("test2")
        s:push("test2")
        eq(2, s:size())
        s:clear()
        eq(0, s:size())
    end)

    it("peek", function()
        s:push(1)
        eq(1, s:peek())
        s:clear()
        eq(nil, s:peek())
    end)
end)
