name: Run tests
on:
  pull_request: ~
  push:
    branches:
      - v2

jobs:
  build:
    name: Run tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        neovim_version: ['v0.10.0', 'nightly']

    steps:
      - uses: actions/checkout@v3
      - name: Run tests
        uses: nvim-neorocks/nvim-busted-action@v1
        with:
          nvim_version: ${{ matrix.neovim_version }}
